name: butter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_storage: ^12.4.7
  firebase_app_check: ^0.3.2+7
  cloud_firestore: ^5.6.9
  shared_preferences: ^2.2.2

  # UI
  pin_code_fields: ^8.0.1
  flutter_launcher_icons: ^0.14.4
  http: ^1.4.0
  flutter_datetime_picker_plus: ^2.0.1
  infinite_scroll_pagination: ^5.0.0
  cached_network_image: ^3.3.0
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2


  # Localisation + formatage de date
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

  # Cupertino Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/background-app.png
    - assets/images/background-liste.png
    - assets/images/bouche.jpg
    - assets/icon/app_icon2.png
    - assets/icon/precedent.png
    - assets/images/home_1.png
    - assets/images/home_2.png
    - assets/images/home_3.png
    - assets/images/LogoName.png
    - assets/images/LogoName_black.png
    - assets/navigation-tools/compte.png
    - assets/navigation-tools/compte_black.png
    - assets/navigation-tools/Explorer.png
    - assets/navigation-tools/Explorer_black.png
    - assets/navigation-tools/favoris.png
    - assets/navigation-tools/favoris_black.png
    - assets/navigation-tools/rechercher.png
    - assets/navigation-tools/rechercher_black.png
    - assets/restau-details-tools/call.png
    - assets/restau-details-tools/horaires.png
    - assets/restau-details-tools/insta.png
    - assets/restau-details-tools/metro.png
    - assets/restau-details-tools/send.png
    - assets/restau-details-tools/website.png
    - assets/direction/centre.png
    - assets/direction/est.png
    - assets/direction/ouest.png

  fonts:
  - family: InriaSans
    fonts:
      - asset: assets/fonts/InriaSans-Regular.ttf
      - asset: assets/fonts/InriaSans-Bold.ttf
        weight: 700
  - family: InriaSerif
    fonts:
      - asset: assets/fonts/InriaSerif-Regular.ttf
      - asset: assets/fonts/InriaSerif-Bold.ttf
        weight: 700

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/app_icon.png"
  image_path_ios: "assets/icon/app_icon.png"
  adaptive_icon_background: "assets/icon/background.png"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  icon_size: 24
