// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuEj74dqtNUtKw-gqEAhATR0F7hF3AT1A',
    appId: '1:743945650254:android:51480737f9e46d5c41831f',
    messagingSenderId: '743945650254',
    projectId: 'butter-vdef',
    storageBucket: 'butter-vdef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNUj-dWcRN19k4jQ_OrZS722LmL1tCBd4',
    appId: '1:743945650254:ios:8c163221d099eb4f41831f',
    messagingSenderId: '743945650254',
    projectId: 'butter-vdef',
    storageBucket: 'butter-vdef.firebasestorage.app',
    androidClientId: '743945650254-ttk954kai9vv16r8s6qnghrkuqcpuvog.apps.googleusercontent.com',
    iosClientId: '743945650254-tk9s4avsim16vdvhj6sh221djk5gck7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.butter-new',
  );
}
